service: abandonai-tiktoken
provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1

plugins:
  - serverless-dotenv-plugin

useDotenv: true

package:
  patterns:
    - "!./**"
    - "./bin/**"
functions:
  tiktoken:
    handler: bin/cmd/tiktoken
    events:
      - http:
          path: /
          method: POST
